language: node_js
sudo: required
dist: trusty
node_js:
  - '6'
cache:
  yarn: true
  directories:
    - node_modules
branches:
  except:
    - /^v\d/
install:
  - yarn install
  - yarn global add bower
  - bower install
script:
  - yarn run lint
  # - yarn run test
before_deploy:
  - >
    if [ $TRAVIS_BRANCH == 'master' ]; then
      yarn run build:production;
    elif [ $TRAVIS_BRANCH == 'develop' ]; then
      yarn run build;
    fi
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: gdg-es-develop
    token: $FIREBASE_TOKEN
    on:
      branch: develop
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: gdg-es
    token: $FIREBASE_TOKEN
    on:
      branch: master
